name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    # https://github.com/actions/cache/blob/master/examples.md#go---modules
    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: golangci-lint
      # You may pin to the exact commit or the version.
      # uses: actions-contrib/golangci-lint@502d94948c3b222dc7f1ce576a25269037600ef9
      uses: actions-contrib/golangci-lint@v1
      with:
        # golangci-lint docker release tag
        golangci_lint_version: v1.38
    
